--- #YAML:1.0
name:               Linux-Unshare
version:            0.05
abstract:           Perl interface for Linux unshare system call.
author:
    - Boris Sukholitko <boris@>
    - Marian Marinov <HackMan>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
resources:
    repository: https://github.com/hackman/Linux-Unshare
    license:    http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
