--- #YAML:1.0
name:                Linux-Unshare
version:             0.01
abstract:            Perl extension for blah blah blah
license:             ~
author:              
    - Boris Sukholitko <boris@>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
